### ISSUE TITLE
Illegal string offset 'RESULT' timemachine_model.php on line 293

### ISSUE THREAD

**Issue by precursorca** [munkireport/timemachine#4]
In munkireport 5.3.5 (php 7.38) there seems to be a problem with line 293 of the timemachine_model.php
Specifically: Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 293

`[Sat Apr 04 09:52:41.233143 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 293
[Sat Apr 04 09:52:41.233179 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP Stack trace:
[Sat Apr 04 09:52:41.233232 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   1. {main}() /Users/Shared/munkireport-php/public/index.php:0
[Sat Apr 04 09:52:41.233277 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   2. require_once() /Users/Shared/munkireport-php/public/index.php:7
[Sat Apr 04 09:52:41.233321 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   3. Engine->__construct() /Users/Shared/munkireport-php/bootstrap/app.php:129
[Sat Apr 04 09:52:41.233366 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   4. Engine->__construct() /Users/Shared/munkireport-php/system/kissmvc.php:17
[Sat Apr 04 09:52:41.233411 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   5. munkireport\\\\controller\\\\Report->check_in() /Users/Shared/munkireport-php/system/kissmvc_core.php:86
[Sat Apr 04 09:52:41.233455 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   6. munkireport\\\\controller\\\\Report->_runModel() /Users/Shared/munkireport-php/app/controllers/Report.php:189
[Sat Apr 04 09:52:41.233500 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   7. Timemachine_model->process() /Users/Shared/munkireport-php/app/controllers/Report.php:280
[Sat Apr 04 09:52:41.233634 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 293
[Sat Apr 04 09:52:41.233671 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP Stack trace:
[Sat Apr 04 09:52:41.233708 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   1. {main}() /Users/Shared/munkireport-php/public/index.php:0
[Sat Apr 04 09:52:41.233746 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   2. require_once() /Users/Shared/munkireport-php/public/index.php:7
[Sat Apr 04 09:52:41.233783 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   3. Engine->__construct() /Users/Shared/munkireport-php/bootstrap/app.php:129
[Sat Apr 04 09:52:41.233820 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   4. Engine->__construct() /Users/Shared/munkireport-php/system/kissmvc.php:17
[Sat Apr 04 09:52:41.233858 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   5. munkireport\\\\controller\\\\Report->check_in() /Users/Shared/munkireport-php/system/kissmvc_core.php:86
[Sat Apr 04 09:52:41.233895 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   6. munkireport\\\\controller\\\\Report->_runModel() /Users/Shared/munkireport-php/app/controllers/Report.php:189
[Sat Apr 04 09:52:41.233933 2020] [php7:notice] [pid 49162] [client 184.71.72.62:52083] PHP   7. Timemachine_model->process() /Users/Shared/munkireport-php/app/controllers/Report.php:280
`

**Comment by tuxudo** [comment]
Please test the issue-5-fix branch to see if this problem is resolved.

**Comment by precursorca** [comment]
I replaced the Time Machine_model.php file with the #5 one on my MunkiReport server and will monitor the results.


---
Alex Narvey
anarvey@precursor.ca

**Comment by precursorca** [comment]
Here is a before and after example:

BEFORE:
[Mon Oct 26 10:31:54.877948 2020] [php7:warn] [pid 86376] [client 184.71.72.62:53158] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 263
[Mon Oct 26 10:31:54.878265 2020] [php7:notice] [pid 86376] [client 184.71.72.62:53158] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[Mon Oct 26 10:31:54.878284 2020] [php7:warn] [pid 86376] [client 184.71.72.62:53158] PHP Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[Mon Oct 26 10:31:54.878297 2020] [php7:notice] [pid 86376] [client 184.71.72.62:53158] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290
[Mon Oct 26 10:31:54.878314 2020] [php7:notice] [pid 86376] [client 184.71.72.62:53158] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294
[Mon Oct 26 10:31:54.878327 2020] [php7:warn] [pid 86376] [client 184.71.72.62:53158] PHP Warning:  Illegal string offset 'RESULT' in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294
[Mon Oct 26 10:31:54.878339 2020] [php7:notice] [pid 86376] [client 184.71.72.62:53158] PHP Notice:  Uninitialized string offset: 0 in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 294


AFTER
[Tue Oct 27 07:23:46.283088 2020] [php7:warn] [pid 93446] [client 184.71.72.62:58661] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 263
[Tue Oct 27 07:23:46.283408 2020] [php7:warn] [pid 93446] [client 184.71.72.62:58661] PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /Users/Shared/munkireport-php/vendor/munkireport/timemachine/timemachine_model.php on line 290




---
Alex Narvey
anarvey@precursor.ca

**Comment by grangeway** [comment]
@tuxudo - Have a similar/same issue - $plist["Destinations" is   string(0) ""

            if (array_key_exists("Destinations",$plist)){
				**if( !is_array ( $plist["Destinations"] ) ) {
					$this->destinations = "0";
				} else {**
					$this->destinations = count($plist["Destinations"]);
				}

and then also

            // Fill in older legacy values
            if (array_key_exists("Destinations", $plist) **&& is_array( $plist["Destinations"] )** && array_key_exists("legacy_output", $plist) && $plist["legacy_output"] == "Mac OS X 10.12+ not supported with legacy Time Machine log output") {

**Comment by tuxudo** [comment]
This should be fixed with the Python 3 version of the module.

**Comment by tuxudo** [comment]
Fixed with v4.0 of module
